// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobileProtocol.proto

package rug.ucProject;

public final class mobileProtocol {
  private mobileProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum CmdType
      implements com.google.protobuf.ProtocolMessageEnum {
    VIBRATION(0, 0),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static CmdType valueOf(int value) {
      switch (value) {
        case 0: return VIBRATION;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CmdType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CmdType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdType>() {
            public CmdType findValueByNumber(int number) {
              return CmdType.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return rug.ucProject.mobileProtocol.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final CmdType[] VALUES = {
      VIBRATION, 
    };
    public static CmdType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private CmdType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      rug.ucProject.mobileProtocol.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:mobileProtocol.CmdType)
  }
  
  public static final class ucMsg extends
      com.google.protobuf.GeneratedMessage {
    // Use ucMsg.newBuilder() to construct.
    private ucMsg() {
      initFields();
    }
    private ucMsg(boolean noInit) {}
    
    private static final ucMsg defaultInstance;
    public static ucMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public ucMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rug.ucProject.mobileProtocol.internal_static_mobileProtocol_ucMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rug.ucProject.mobileProtocol.internal_static_mobileProtocol_ucMsg_fieldAccessorTable;
    }
    
    // required .mobileProtocol.CmdType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private rug.ucProject.mobileProtocol.CmdType type_;
    public boolean hasType() { return hasType; }
    public rug.ucProject.mobileProtocol.CmdType getType() { return type_; }
    
    // repeated int64 vPattern = 2;
    public static final int VPATTERN_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Long> vPattern_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Long> getVPatternList() {
      return vPattern_;
    }
    public int getVPatternCount() { return vPattern_.size(); }
    public long getVPattern(int index) {
      return vPattern_.get(index);
    }
    
    private void initFields() {
      type_ = rug.ucProject.mobileProtocol.CmdType.VIBRATION;
    }
    public final boolean isInitialized() {
      if (!hasType) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeEnum(1, getType().getNumber());
      }
      for (long element : getVPatternList()) {
        output.writeInt64(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getType().getNumber());
      }
      {
        int dataSize = 0;
        for (long element : getVPatternList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getVPatternList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static rug.ucProject.mobileProtocol.ucMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rug.ucProject.mobileProtocol.ucMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rug.ucProject.mobileProtocol.ucMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rug.ucProject.mobileProtocol.ucMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rug.ucProject.mobileProtocol.ucMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rug.ucProject.mobileProtocol.ucMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rug.ucProject.mobileProtocol.ucMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rug.ucProject.mobileProtocol.ucMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rug.ucProject.mobileProtocol.ucMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rug.ucProject.mobileProtocol.ucMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rug.ucProject.mobileProtocol.ucMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private rug.ucProject.mobileProtocol.ucMsg result;
      
      // Construct using rug.ucProject.mobileProtocol.ucMsg.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new rug.ucProject.mobileProtocol.ucMsg();
        return builder;
      }
      
      protected rug.ucProject.mobileProtocol.ucMsg internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new rug.ucProject.mobileProtocol.ucMsg();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rug.ucProject.mobileProtocol.ucMsg.getDescriptor();
      }
      
      public rug.ucProject.mobileProtocol.ucMsg getDefaultInstanceForType() {
        return rug.ucProject.mobileProtocol.ucMsg.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public rug.ucProject.mobileProtocol.ucMsg build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private rug.ucProject.mobileProtocol.ucMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public rug.ucProject.mobileProtocol.ucMsg buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.vPattern_ != java.util.Collections.EMPTY_LIST) {
          result.vPattern_ =
            java.util.Collections.unmodifiableList(result.vPattern_);
        }
        rug.ucProject.mobileProtocol.ucMsg returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rug.ucProject.mobileProtocol.ucMsg) {
          return mergeFrom((rug.ucProject.mobileProtocol.ucMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rug.ucProject.mobileProtocol.ucMsg other) {
        if (other == rug.ucProject.mobileProtocol.ucMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.vPattern_.isEmpty()) {
          if (result.vPattern_.isEmpty()) {
            result.vPattern_ = new java.util.ArrayList<java.lang.Long>();
          }
          result.vPattern_.addAll(other.vPattern_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              rug.ucProject.mobileProtocol.CmdType value = rug.ucProject.mobileProtocol.CmdType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setType(value);
              }
              break;
            }
            case 16: {
              addVPattern(input.readInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addVPattern(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // required .mobileProtocol.CmdType type = 1;
      public boolean hasType() {
        return result.hasType();
      }
      public rug.ucProject.mobileProtocol.CmdType getType() {
        return result.getType();
      }
      public Builder setType(rug.ucProject.mobileProtocol.CmdType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = rug.ucProject.mobileProtocol.CmdType.VIBRATION;
        return this;
      }
      
      // repeated int64 vPattern = 2;
      public java.util.List<java.lang.Long> getVPatternList() {
        return java.util.Collections.unmodifiableList(result.vPattern_);
      }
      public int getVPatternCount() {
        return result.getVPatternCount();
      }
      public long getVPattern(int index) {
        return result.getVPattern(index);
      }
      public Builder setVPattern(int index, long value) {
        result.vPattern_.set(index, value);
        return this;
      }
      public Builder addVPattern(long value) {
        if (result.vPattern_.isEmpty()) {
          result.vPattern_ = new java.util.ArrayList<java.lang.Long>();
        }
        result.vPattern_.add(value);
        return this;
      }
      public Builder addAllVPattern(
          java.lang.Iterable<? extends java.lang.Long> values) {
        if (result.vPattern_.isEmpty()) {
          result.vPattern_ = new java.util.ArrayList<java.lang.Long>();
        }
        super.addAll(values, result.vPattern_);
        return this;
      }
      public Builder clearVPattern() {
        result.vPattern_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:mobileProtocol.ucMsg)
    }
    
    static {
      defaultInstance = new ucMsg(true);
      rug.ucProject.mobileProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:mobileProtocol.ucMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mobileProtocol_ucMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mobileProtocol_ucMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024mobileProtocol.proto\022\016mobileProtocol\"@" +
      "\n\005ucMsg\022%\n\004type\030\001 \002(\0162\027.mobileProtocol.C" +
      "mdType\022\020\n\010vPattern\030\002 \003(\003*\030\n\007CmdType\022\r\n\tV" +
      "IBRATION\020\000B\037\n\rrug.ucProjectB\016mobileProto" +
      "col"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mobileProtocol_ucMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mobileProtocol_ucMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mobileProtocol_ucMsg_descriptor,
              new java.lang.String[] { "Type", "VPattern", },
              rug.ucProject.mobileProtocol.ucMsg.class,
              rug.ucProject.mobileProtocol.ucMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
